version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/code/src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/code"
    schedule:
      interval: "weekly"
